### PR TITLE
Update henry.py

### PR DESCRIPTION
**Pull request by wanda-carlson**

### CODE REVIEW

**Comment by wanda-carlson** [comment]
comment

**Review by sarah-paidpaper — COMMENTED** [review]
Good

**Comment by henry-richard** [comment]
old PR

**Comment by henry-richard** [comment]
test

**Comment by henry-richard** [comment]
Test
[Screenshot 2024-01-05 at 3.46.45 PM.png](https://files.slack.com/files-pri/T0289BY1FK4-F06F6GW7KLL/screenshot_2024-01-05_at_3.46.45_pm.png)

**Comment by henry-richard** [comment]
Test
test
_test_
* **testTest**
* test
1. test
2. **testTest**
3. test
4. ~test~
5. test
Test
>test
test
test
Test
`test`
```
test
test
```

**Comment by henry-richard** [comment]
Screenshot 2024-01-05 at 3 46 45 PM
comments

**Review by henry-richard — COMMENTED** [review]
what?

**Review by henry-richard — CHANGES_REQUESTED** [review]
change it

**Pull request merged**
